#!/usr/bin/env bash
# Idempotent RunPod bootstrap.
#
# This file is intended to be sourced:
#   source /workspace/mllm_hwsi_ah/scripts/runpod_bootstrap.sh
# All durable state created here lives under /workspace.

set -euo pipefail

WORKSPACE_ROOT="${WORKSPACE_ROOT:-/workspace}"
PROJECT_DIR="${PROJECT_DIR:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)}"
CAN_ROOT="${CAN_ROOT:-$WORKSPACE_ROOT/datasets/can_dataset}"
VENV_DIR="${VENV_DIR:-$WORKSPACE_ROOT/venvs/mllm_hwsi_ah}"
BIN_DIR="${BIN_DIR:-$WORKSPACE_ROOT/bin}"
STATE_DIR="${STATE_DIR:-$WORKSPACE_ROOT/.mllm_hwsi_ah}"
ENV_FILE="$STATE_DIR/env.sh"

mkdir -p "$VENV_DIR" "$BIN_DIR" "$STATE_DIR"

install_tmux() {
    if command -v tmux >/dev/null 2>&1; then
        echo "[bootstrap] tmux=$(command -v tmux)"
        return 0
    fi
    if [[ -x "$BIN_DIR/tmux" ]]; then
        export PATH="$BIN_DIR:$PATH"
        echo "[bootstrap] tmux=$BIN_DIR/tmux (persistent static fallback)"
        return 0
    fi
    if [[ "$(id -u)" == "0" ]] && command -v apt-get >/dev/null 2>&1; then
        echo "[bootstrap] tmux missing; attempting apt-get install"
        if apt-get update -qq && apt-get install -y -qq tmux; then
            echo "[bootstrap] tmux=$(command -v tmux)"
            return 0
        fi
        echo "[bootstrap] apt-get tmux failed; trying /workspace/bin/tmux"
    fi
    cat >&2 <<EOF
[bootstrap] ERROR: tmux is unavailable.
Upload a Linux static tmux binary to $BIN_DIR/tmux, chmod +x it,
then source this script again.  The binary must remain on the attached
/workspace volume; a pod/container root filesystem is not durable.
EOF
    return 1
}

install_python_env() {
    local host_python="${PYTHON_HOST:-python3}"
    if [[ ! -x "$VENV_DIR/bin/python" ]]; then
        echo "[bootstrap] creating venv at $VENV_DIR"
        "$host_python" -m venv --system-site-packages "$VENV_DIR"
    fi
    # Use the venv's interpreter by absolute path so reboot paths are stable.
    "$VENV_DIR/bin/python" -m pip install --upgrade pip >/dev/null
    "$VENV_DIR/bin/python" -m pip install -r "$PROJECT_DIR/requirements-nav.txt"
}

write_env_file() {
    local git_name="${GIT_USER_NAME:-AaronHung (runpod)}"
    local git_email="${GIT_USER_EMAIL:-aaron@users.noreply.github.com}"
    cat >"$ENV_FILE" <<EOF
# Generated by scripts/runpod_bootstrap.sh; persistent under /workspace.
export PROJECT_DIR=$(printf '%q' "$PROJECT_DIR")
export CAN_ROOT=$(printf '%q' "$CAN_ROOT")
export VENV_DIR=$(printf '%q' "$VENV_DIR")
export PYTHON_BIN=$(printf '%q' "$VENV_DIR/bin/python")
export RUN_ROOT=$(printf '%q' "$PROJECT_DIR/runs/v2")
export PYTHONPATH=$(printf '%q' "$PROJECT_DIR")
export PYTORCH_ENABLE_MPS_FALLBACK=1
export GIT_USER_NAME=$(printf '%q' "$git_name")
export GIT_USER_EMAIL=$(printf '%q' "$git_email")
EOF
    printf 'export PATH=%q:$PATH\n' "$BIN_DIR:$VENV_DIR/bin" >>"$ENV_FILE"
    # The identity is local to this clone; no credential/token is written.
    git -C "$PROJECT_DIR" config user.name "$git_name"
    git -C "$PROJECT_DIR" config user.email "$git_email"
    # shellcheck disable=SC1090
    source "$ENV_FILE"
    echo "[bootstrap] env=$ENV_FILE"
    echo "[bootstrap] PROJECT_DIR=$PROJECT_DIR"
    echo "[bootstrap] CAN_ROOT=$CAN_ROOT"
    echo "[bootstrap] python=$VENV_DIR/bin/python"
}

install_tmux
install_python_env
write_env_file

echo "[bootstrap] torch/cuda:"
"$VENV_DIR/bin/python" - <<'PY'
import torch
print("  torch", torch.__version__)
print("  cuda_available", torch.cuda.is_available())
print("  mps_available", torch.backends.mps.is_available())
PY

echo "[bootstrap] verifying persistent data and committed checksums"
PROJECT_DIR="$PROJECT_DIR" CAN_ROOT="$CAN_ROOT" \
    bash "$PROJECT_DIR/scripts/verify_runpod_data.sh"

echo "[bootstrap] PASS — environment and data are ready."
