#!/usr/bin/env bash
# Idempotent RunPod bootstrap.
#
# This file is intended to be sourced:
#   source /workspace/mllm_hwsi_ah/scripts/runpod_bootstrap.sh
# All durable state created here lives under /workspace.

set -euo pipefail

WORKSPACE_ROOT="${WORKSPACE_ROOT:-/workspace}"
PROJECT_DIR="${PROJECT_DIR:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)}"
CAN_ROOT="${CAN_ROOT:-$WORKSPACE_ROOT/datasets/can_dataset}"
VENV_DIR="${VENV_DIR:-$WORKSPACE_ROOT/venvs/mllm_hwsi_ah}"
BIN_DIR="${BIN_DIR:-$WORKSPACE_ROOT/bin}"
STATE_DIR="${STATE_DIR:-$WORKSPACE_ROOT/.mllm_hwsi_ah}"
ENV_FILE="$STATE_DIR/env.sh"

mkdir -p "$VENV_DIR" "$BIN_DIR" "$STATE_DIR"

install_tmux() {
    if command -v tmux >/dev/null 2>&1; then
        echo "[bootstrap] tmux=$(command -v tmux)"
        return 0
    fi
    if [[ -x "$BIN_DIR/tmux" ]]; then
        export PATH="$BIN_DIR:$PATH"
        echo "[bootstrap] tmux=$BIN_DIR/tmux (persistent static fallback)"
        return 0
    fi
    if [[ "$(id -u)" == "0" ]] && command -v apt-get >/dev/null 2>&1; then
        echo "[bootstrap] tmux missing; attempting apt-get install"
        if apt-get update -qq && apt-get install -y -qq tmux; then
            echo "[bootstrap] tmux=$(command -v tmux)"
            return 0
        fi
        echo "[bootstrap] apt-get tmux failed; trying /workspace/bin/tmux"
    fi
    cat >&2 <<EOF
[bootstrap] ERROR: tmux is unavailable.
Upload a Linux static tmux binary to $BIN_DIR/tmux, chmod +x it,
then source this script again.  The binary must remain on the attached
/workspace volume; a pod/container root filesystem is not durable.
EOF
    return 1
}

install_rsync() {
    # Needed on both ends of any Mac -> RunPod data transfer (rsync launches
    # `rsync --server` remotely over the existing ssh connection); minimal
    # CUDA base images typically ship without it. Same install pattern as
    # install_tmux above; a missing rsync only breaks large data uploads
    # (e.g. pilot40's brca_pilot40_k48/), not training itself, so this is a
    # best-effort step, not a hard bootstrap failure.
    if command -v rsync >/dev/null 2>&1; then
        echo "[bootstrap] rsync=$(command -v rsync)"
        return 0
    fi
    if [[ "$(id -u)" == "0" ]] && command -v apt-get >/dev/null 2>&1; then
        echo "[bootstrap] rsync missing; attempting apt-get install"
        if apt-get update -qq && apt-get install -y -qq rsync; then
            echo "[bootstrap] rsync=$(command -v rsync)"
            return 0
        fi
    fi
    echo "[bootstrap] WARNING: rsync unavailable and could not be installed" \
         "(not root, or apt-get failed); large data transfers will need" \
         "scp instead (no resume support)." >&2
}

install_python_env() {
    local host_python="${PYTHON_HOST:-python3}"
    if [[ ! -x "$VENV_DIR/bin/python" ]]; then
        echo "[bootstrap] creating venv at $VENV_DIR"
        "$host_python" -m venv --system-site-packages "$VENV_DIR"
    fi
    # Use the venv's interpreter by absolute path so reboot paths are stable.
    "$VENV_DIR/bin/python" -m pip install --upgrade pip >/dev/null
    "$VENV_DIR/bin/python" -m pip install -r "$PROJECT_DIR/requirements-nav.txt"
}

write_env_file() {
    local git_name="${GIT_USER_NAME:-AaronHung (runpod)}"
    local git_email="${GIT_USER_EMAIL:-aaron@users.noreply.github.com}"
    cat >"$ENV_FILE" <<EOF
# Generated by scripts/runpod_bootstrap.sh; persistent under /workspace.
export PROJECT_DIR=$(printf '%q' "$PROJECT_DIR")
export CAN_ROOT=$(printf '%q' "$CAN_ROOT")
export VENV_DIR=$(printf '%q' "$VENV_DIR")
export PYTHON_BIN=$(printf '%q' "$VENV_DIR/bin/python")
export RUN_ROOT=$(printf '%q' "$PROJECT_DIR/runs/v2")
export PYTHONPATH=$(printf '%q' "$PROJECT_DIR")
export PYTORCH_ENABLE_MPS_FALLBACK=1
export GIT_USER_NAME=$(printf '%q' "$git_name")
export GIT_USER_EMAIL=$(printf '%q' "$git_email")
EOF
    printf 'export PATH=%q:$PATH\n' "$BIN_DIR:$VENV_DIR/bin" >>"$ENV_FILE"
    # Two-line colored prompt: a fresh container resets /root/.bashrc, so this
    # lives here (persistent under /workspace) and is re-applied every time
    # env.sh is sourced. Yellow username, dim separator, cyan full path, git
    # branch in magenta when inside a repo; the bare `$`/`#` prompt symbol
    # sits alone on its own line so it is easy to tell commands apart from
    # output in long scrollback, and easy to copy cleanly.
    cat >>"$ENV_FILE" <<'PSEOF'
__mllm_git_branch() { git symbolic-ref --short HEAD 2>/dev/null; }
export PS1='\[\033[1;33m\]\u\[\033[0m\] \[\033[2m\]|\[\033[0m\] \[\033[1;36m\]\w\[\033[0m\]\[\033[35m\]$(b=$(__mllm_git_branch); [ -n "$b" ] && printf " (%s)" "$b")\[\033[0m\]\n\$ '
PSEOF
    # The identity is local to this clone; no credential/token is written.
    git -C "$PROJECT_DIR" config user.name "$git_name"
    git -C "$PROJECT_DIR" config user.email "$git_email"
    # shellcheck disable=SC1090
    source "$ENV_FILE"
    echo "[bootstrap] env=$ENV_FILE"
    echo "[bootstrap] PROJECT_DIR=$PROJECT_DIR"
    echo "[bootstrap] CAN_ROOT=$CAN_ROOT"
    echo "[bootstrap] python=$VENV_DIR/bin/python"
    echo "[bootstrap] PS1 updated (yellow user | cyan path (git branch), prompt on its own line)"
}

install_tmux
install_rsync
install_python_env
write_env_file

echo "[bootstrap] torch/cuda:"
"$VENV_DIR/bin/python" - <<'PY'
import torch
print("  torch", torch.__version__)
print("  cuda_available", torch.cuda.is_available())
print("  mps_available", torch.backends.mps.is_available())
PY

echo "[bootstrap] verifying persistent data and committed checksums"
PROJECT_DIR="$PROJECT_DIR" CAN_ROOT="$CAN_ROOT" \
    bash "$PROJECT_DIR/scripts/verify_runpod_data.sh"

echo "[bootstrap] PASS — environment and data are ready."
